# Author: 潘维吉
# Description: 云原生K8S中使用cert-manager基于 ACME 协议与 Let's Encrypt 自动签发与续签免费的SSL证书

# 创建一个集群级的签发机构  仅需一次  证书生成需要等待1分钟左右  域名解析ip正确 ingressClassName指定正确  Let's Encrypt限制每个 IP 地址每 3 小时最多可以请求 5 个证书 超出请分批执行创建证书
# 重新生成证书 kubectl delete clusterissuer  issuerName 和 kubectl --namespace cert-manager  delete  Secret  letsencrypt-prod-key
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-letsencrypt-prod-k8s-self-built-main-data
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  # ACME 协议的服务端  acme-staging-v02测试证书没有限制
    email: 406798106@qq.com  # 证书快过期的时候会有邮件提醒
    privateKeySecretRef:
      name: my-letsencrypt-prod-key-k8s-self-built-main-data  # 私钥秘密必须与cert-manager服务在同一个命名空间中才能工作 kubectl delete Secret letsencrypt-prod-key --namespace cert-manager
    solvers:
      - http01: # 签发机构使用 HTTP-01 的方式进行 acme 协议 (还可用 DNS 方式，acme 协议的目的是证明机器和域名都是属于你的，然后才准许颁发证书)
          ingress:
            #serviceType: ClusterIP
            name: ingress-k8s-self-built-main-data # 这个匹配是关键！！！  1. class是指定自动创建的 Ingress 的 ingress class  2. name是指定被自动修改的 Ingress 名称

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-k8s-self-built-main-data
  namespace: default
  annotations:
    # add an annotation indicating the issuer to use
    cert-manager.io/cluster-issuer: my-letsencrypt-prod-k8s-self-built-main-data
    acme.cert-manager.io/http01-edit-in-place: "true"
    # 后端大文件上传大小
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1024m
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: 2048m
    # 数据传输大小
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    # 开启CORS跨域请求
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-max-age: "64800"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    # 配置是否同时支持http和https访问应用
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - main-data-self-k8s-admin.pengbocloud.com
      secretName: my-main-data-self-k8s-admin.pengbocloud.com-tls

  rules:
    #自定义域名
    - host: main-data-self-k8s-admin.pengbocloud.com
      http:
        paths:
          - path: /
            backend:
              #服务名称
              service:
                name: main-data-admin-web-self-built-service
                #服务端口
                port:
                  number: 9109
            pathType: Prefix